### ISSUE TITLE
question: netns-exec + tmux

### ISSUE THREAD

**Issue by atmosx** [pekman/netns-exec#3]
Using `netns-exec` with `tmux` leads to a situation where every new user `tmux` session will drop the session in the `netns` namespace. Example:

```bash
[create `sample` netns, bring up network interfaces, etc.]
$ ip netns list
sample (id: 4)
$ netns-exec sample tmux new -s sample
$ tmux new -s pingo
$ ifconfig
...
```

Now the `pingo` session runs in the `sample` namespace. Why is that? 🤔

**Comment by pekman** [comment]
This has nothing to do with `netns-exec` specifically. It turns out that `tmux` uses a common server process for differently named sessions, and this process of course gets its network namespace (and other such attributes) from the first `tmux new` call. (Yes, I have run into this problem too.) A separate `tmux` process can be started with the `-L` option, so this should work:

```
netns-exec sample tmux -L sample new
tmux -L pingo new
```

Closing this issue as it's not a problem in `netns-exec`.
